package com.skooltchdev.multiplechoicequiz;


public class QuestionLibrary {

    private String mQuestions [] = {
            //chapter1
            "1.An operating system is a program that manages a computer’s hardware.",
            "2.A ............. manages the execution of user programs to prevent errors and improper use of the computer.",
            "3. ...........can be structured asymmetrically or symmetrically.",
            "4.Other forms of clusters include parallel clusters and clustering over a .......... ",
            "5.A single program ....., in general, keep either the CPU or the I/O devices busy at all times.",
            "6............... is a logical extension of multiprogramming.",
            "7.In a ........... linked list, each item points to its successor.",
            "8.In a ......... linked list, a given item can refer either to its predecessor or to its successor",
            "9. In a ........... linked list, the last element in the list refers to the ﬁrst element,rather than to null.",
            "10.A ........ is a sequentially ordered data structure that uses the LIFO principle for adding and removing items",
            "11.A queue is a sequentially ordered data structure that uses the ......... principle",
            "12.A ........ is a data structure that can be used to represent data hierarchically ",
            "13. In a binary tree, a parent may have at most....... children.",
            "14.The occurrence of an ......... is usually signaled by an interruptfrom either the hardware or the software",
            "15.A ....... can contain one of two values,0and1",
            "16. A.........is a software-generated interrupt caused either by an error or by a speciﬁc request from a user program",
            "17.A single-threaded process has ........ program counter specifying the next instruction to execute. ",
            "18.A bit map is a string of n binary digits that can be used to represent the status of ..... items.",
            "19. A ..........-sized disk drive might be divided into several thousand individual units, called disk blocks",
            "20............... refers to computing on handheld smartphones and tablet computers. ",
            "21.The .......-server system provides an interface to which a client can send a request to perform an action",
            "22. The ........-server system provides a ﬁle-system interface where clients can create,update,read,and delete ﬁles",
            "23...........computing is a type of computing that delivers computing, storage, and even applications as a service across a network",
            "24.Main function of shared memory is:",
            "25.Belady anamoly occurs in",
            "26. Which among following scheduling algorithms give minimum average waiting time",
            "27.Size of virtual memory depends on",
            "28.In which scheduling policies, context switching never takes place",
            "29.Which is single user operating system",
            "30.Macintosh computer uses",
            "31.Creating a job queue is a function of",
            "32.Which operating system use write through catches",
            "33.Which process is known for initializing a microcomputer with its OS",
            "34.Which of the following does not interrupt an running process",
            "35.Dijkstra's algorithm deals with",
            "36.A series of statements explaining how the data is to be processed is called",
            "37.Which is non pre-emptive",
            "38.A hardware device which is capable of executing a sequence of instructions, is known as",
            "39.Which of following is not a condition of Dead Lock?",
            "40.To avoid the race condition, the number of processes that may be simultaneously inside the critical section is",

            //chapter2
            "1.What does every OS use to organize a hard drive, optical drive, floppy disk, or USB drive?",
            "2.Different versions of Unix or Linux are sometimes called................?",
            "3.Which of the following manages hardware runs applications provides interface for users stores, retrieves, and manipulates files?",
            "4.Mac OS X provides superior Plug and Play capabilities and better support for multitasking.",
            "5.Which of the following gives a wealth of information about installed hardware and software?",
            "6.Using Explorer or the Computer window, you can view and change the properties assigned to a file.What are these properties called?",
            "7.A file extension identifies which of the following?",
            "8.Which of the following is NOT an available option for launching an application?",
            "9.With an icon-driven interface, sometimes called a(n)........., you perform operations by clicking icons on the screen.",
            "10.The Windows System Tray contains quick launch icons.",
            "11.Another name for a logical drive is volume.",
            "12.Which one of the following is NOT a type of software?",
            "13.Recycle Bin are not really deleted until you empty the bin.",
            "14..........are small programs stored on the hard drive that tell the computer how to communicate with a speciﬁc hardware device ",
            "15.The Control Panel in Windows would be most similar to..........on a Mac.",
            "16.Which of the following is an upgrade from Windows 2000 and provides added support for multimedia and networking technologies?",
            "17.Which of the following operating system has been used in troubleshooting OS failures?",
            "18.What is normally located at the bottom of the Windows desktop, displaying information about open programs.",
            "19.In some troubleshooting situations,the mouse is not usable.At those times, knowing the .........can get you out of a jam.",
            "20.Which of the following is the primary Windows tool that can be used when solving problems with hardware?",
            "21.Which of the following is a window containing several small utility programs called applets.",
            "22.With a ..............interface, you type commands to tell the OS to perform operations.",
            "23.What is the first Windows OS to allow multiple users to log on simultaneously to the OS.",
            "24.From the Windows desktop, you can launch programs from the Start menu, a shortcut icon on the desktop.",
            "25.An OS manages ﬁles and folders using a ﬁle system. Two Windows ﬁle systems are FAT and.............",
            "26.CPU's operate in one of a possible how many modes?",
            "27.Which of the following is a major update or fix to an OS occasionally released by Microsoft?",
            "28. ..............is built directly on the hardware.",
            "29............Operating System does not implement multitasking.",
            "30.When a process fails, most OS write the error information to a ...........",

            //ch3 process concets
            "1.The systems which allow only one process execution at a time, are called.............",
            "2.In operating system, each process has its own ..........",
            "3.In Unix, Which system call creates the new process?",
            "4.A process can be terminated due to ............",
            "5.What is the ready state of a process?",
            "6.What is interprocess communication?",
            "7.A set of processes is deadlock if ",
            "8.A process stack does not contain ............",
            "9.Which system call returns the process identifier of a terminated child?",
            "10.The address of the next instruction to be executed by the current process is provided by..........",
            "11.The number of processes completed per unit time is known as",
            "12.Which of the following is not the state of a process?",
            "13.What is a Process Control Block?",
            "14.The entry of all the PCBs of the current processes is in ........",
            "15.A single thread of control allows the process to perform........",
            "16.Which of the following do not belong to queues for processes?",
            "17.The only state transition that is initiated by the user process itself is",
            "18.The context of a process in the PCB of a process does not contain",
            "19.Which of the following does not interrupt a running process?",
            "20.Which process can be affected by other processes executing in the system?",
            "21.In UNIX, each process is identified by its ",
            "22.The child process completes execution, but the parent keeps executing, then the child process is known as",
            "23.A parent process calling...........system call will be suspended until children processes terminate.",
            "24.Cascading termination refers to termination of all child processes before the parent terminates........",
            "25.Messages sent by a process ",
            "26.The link between two processes P and Q to send and receive messages is called..............",
            "27.Bounded capacity and Unbounded capacity queues are referred to as................",
            "28.The Zero Capacity queue",
            "29.Which of the following two operations are provided by the IPC facility?",
            "30.In the Zero capacity queue ",
            //ch4
            "1.Which one of the following is not shared by threads?",
            "2.A process can be.............",
            "3.When the event for which a thread is blocked occurs?",
            "4.Termination of the process terminates.............",
            "5.Which one of the following is not a valid state of a thread?",
            "6.The register context and stacks of a thread are deallocated when the thread?",
            "7.In java multi-threading, a thread can be created by..........",
            "8.Which method is called internally by Thread start() method?",
            "9.What is maximum thread priority in Java",
            "10.Which method must be implemented by a Java thread?",
            "11.Execution of a java thread begins on which method call?",
            "12.How many ways a thread can be created in Java multithreading?",
            "13.Which method is used to make main thread to wait for all child threads",
            "14.Default value of a java thread is",
            "15.Which method is used to check if a thread is running?",
            "16.Min and Max priority of a thread in Java multithreading are",
            "17.Which method we implement from Runnable interface?",
            "18.Daemon thread runs in...........",
            "19.Which method is used to create a daemon thread?",
            "20.Which method is used to wait for child threads to finish in Java?",
            "21.Which will contain the body of the thread in Java?",
            "22.The life cycle of a thread in java is controlled by",
            "23.Which method is used to get current running thread object?",
            "24.Which of these are types of multitasking?",
            "25.Thread priority in Java is?",
            //ch 5
            "1.The module that gives control of the CPU to the process selected by the short-term scheduler is?",
            "2.The processes that are ready to be executed and are residing in main memory are kept in",
            "3.When CPU becomes idle which scheduler is called?",
            "4.FCFS algorithm is implemented using",
            "5.Which algorithm suffers from Convoy Effect?",
            "6.What is the problem that arrives while using SJF algorithm?",
            "7.Round robin scheduling falls under the category of ...............",
            "8.Complex scheduling algorithms ...........",
            "9.Orders are processed in the sequence they arrive if ........ rule sequences the jobs",
            "10.Which of the following algorithms tends to minimize the process flow time?",
            "11.Which of the following can not be scheduled by the kernel?",
            "12.If........ rule sequences the jobs Orders are processed in the sequence they arrive",
            "13.Select one which algorithms tend to minimize the process flow time?",
            "14.A program that is bound by CPU might have",
            "15.scheduling algorithm which allocates the CPU first to the process which requests the CPU first?",
            "16.From the time of submission of a process to the time of completion, The interval is termed as",
            "17.under the category of........ Round-robin scheduling falls :",
            "18.control of the CPU to the process selected by the short-term scheduler is assigned by the module.........",
            "19.CPU performance is measured through ....... ",
            "20...........does the job of allocating a process to the processor. ",
            "21..........is the actual decision of which ready process to execute next.",
            "22........may limit the degree of multi-programming to provide service of the current set of process.",
            "23..........executes infrequently and makes the coarse-grained decision of whether or not to take on new process.",
            "24.........establish a set of scheduling queues and allocate processes to queues on execution history and other criteria.",
            "25.........algorithm select the process that has been waiting the longest for service.",
            //ch6
            "1.Which process can be affected by other processes executing in the system?",
            "2.Which one of the following is a synchronization tool?",
            "3.A semaphore is a shared integer variable ..........",
            "4.Mutual exclusion can be provided by the..........",
            "5.Process synchronization can be done on............",
            "6.A monitor is a module that encapsulates.......... ",
            "7.Concurrent access to shared data may result in...........",
            "8.Which of the following conditions must be satisfied to solve the critical section problem?",
            "9.An un-interruptible unit is known as..........",
            "10.TestAndSet instruction is executed ............",
            "11.Semaphore is a/an.......... to solve the critical section problem.",
            "12.What are the two atomic operations permissible on semaphores?",
            "13.The wait operation of the semaphore basically works on the basic........system call.",
            "14.The signal operation of the semaphore basically works on the basic.........system call.",
            "15.The code that changes the value of the semaphore is..........",
            "16.What will happen if a non-recursive mutex is locked more than once?",
            "17.What are the two kinds of semaphores?",
            "18.A binary semaphore is a semaphore with integer values.........",
            "19.Semaphores are mostly used to implement..........",
            "20.Spinlocks are intended to provide..........only.",
            "21.A monitor is a type of..........",
            "22.What are the operations that can be invoked on a condition variable?",
            "23.A collection of instructions that performs a single logical function is called........",
            "24.In the write ahead logging a ............ is maintained.",
            "25.The two phase locking protocol consists of.........",
            //ch7
            "1.Which one of the following is the deadlock avoidance algorithm?",
            "2.A problem encountered in multitasking when process is perpetually denied necessary resources is called.......",
            "3.Which one of the following is a visual ( mathematical ) way to determine the deadlock occurrence?",
            "4.The request and release of resources are..........",
            "5.What are Multithreaded programs?",
            "6.For a deadlock to arise, which of the following conditions must hold simultaneously?",
            "7.For non sharable resources like a printer, mutual exclusion..........",
            "8.For sharable resources, mutual exclusion...........",
            "9.A system is in a safe state only if there exists a..........",
            "10.All unsafe states are.......",
            "11.The Banker’s algorithm is..........than the resource allocation graph algorithm.",
            "12.The data structures available in the Banker’s algorithm are..........",
            "13.The content of the matrix Need is.........",
            "14.If deadlocks occur frequently, the detection algorithm must be invoked............",
            "15.A deadlock eventually cripples system throughput and will cause the CPU utilization to..........",
            "16.Those processes should be aborted on occurrence of a deadlock, the termination of which?",
            "17.The process to be aborted is chosen on the basis of the following factors?",
            "18.If we preempt a resource from a process, the process cannot continue with normal execution.......",
            "19.To........to a safe state, the system needs to keep more information about the states of processes.",
            "20.If the resources are always preempted from the same process.........can occur.",
            "21..........is one that can be created and destroyed.",
            "22.Interrupts, signals, messages and information in I/O buffers are the examples of.........",
            "23............is needed to ensure consistency of results and integrity of a database.",
            "24.Invoking periodically to test for deadlock is one of the ways for deadlock..........",
            "25.A direct method of deadlock prevention is to prevent the occurrence of a.........",
            //ch8
            "1.CPU fetches the instruction from memory according to the value of..........",
            "2.A memory buffer used to accommodate a speed differential is called.............",
            "3.Which one of the following is the address generated by CPU?",
            "4.Run time mapping from virtual to physical address is done by..........",
            "5.The address of a page table in memory is pointed by................",
            "6.Program always deals with............",
            "7.The page table contains.........",
            "8.Operating System maintains the page table for..........",
            "9.The address generated by the CPU is referred to as........",
            "10.The address loaded into the memory address register of the memory is referred to as........",
            "11.The base register is also known as the..........",
            "12.The size of a process is limited to the size of..........",
            "13.Swapping requires a........",
            "14.The major part of swap time is ..........time.",
            "15.Swap space is allocated.........",
            "16.The main memory accommodates..............",
            "17.With relocation and limit registers, each logical address must be..........the limit register.",
            "18.Using transient code,.............the size of the operating system during program execution.",
            "19.When memory is divided into several fixed sized partitions, each partition may contain.........",
            "20.In fixed size partition, the degree of multiprogramming is bounded by........",
            "21.Physical memory is broken into fixed-sized blocks called",
            "22.Logical memory is broken into blocks of the same size called.......",
            "23.The.............is used as an index into the page table.",
            "24.The.............table contains the base address of each page in physical memory.",
            "25.The size of a page is typically...........",
            };


    private String mChoices [][] = {
            //chapter1
            {"hardware", "Software", "ROM"},
            {"system program", "program control", "operating system"},
            {"deadlocks", "scheduling", "Clustering"},
            {"WAN", "MAN", "LAN"},
            {"can", "can not", "none"},
            {"time sharing", "clustering", "response time"},
            {"singly", "doubly", "circularly"},
            {"singly", "doubly", "circularly"},
            {"singly", "doubly", "circularly"},
            {"deadlocks", "stack", "queue"},
            {"FIFO", "LIFO", "none"},
            {"tree", "stack", "queue"},
            {"one", "two", "three"},
            {"event", "scheduling", "stack"},
            {"byte", "bit", "mega byte"},
            {"trap", "interrupt", "logic"},
            {"one", "two", "three"},
            {"0", "1", "n"},
            {"medium", "large", "small"},
            {"mobile computing", "buffering", "modulation"},
            {"compute", "file", "none"},
            {"file", "none", "compute"},
            {"android", "system", "cloud"},
            {"to use primary memory efficently", "intra process communication", "to do inter process communication"},
            {"FIFO","LRU","both"},
            {"FCFS","SJF","Round Robin"},
            {"size of main memory","size of address bus","size of data bus"},
            {"FCFS","SJF","round robin"},
            {"MS DOS","UNIX","LINUX"},
            {"System 7.0","AU/X","Xenix"},
            {"Spooler","Interperator","Complier"},
            {"UNIX","XENIX","DOS"},
            {"cold booting","boot recording","booting"},
            {"A device","Timer","Schedular Process"},
            {"mutual exclusion","deadlock recovery","deadlock avoidance"},
            {"program","compiler","instruction"},
            {"FIFO","SJF","Round Robin"},
            {"Processor","CPU","ALU"},
            {"Mutual Exclusion","No Preemption","Data Transfer"},
            {"0","1","2"},
//chapter2
            {"Executive services and threads","Directories,sub directories and files","Device drivers and volumes"},
            {"Leopard","Distributions","Directories"},
            {"Virtual machine","Systray","Operating system"},
            {"true","false","none"},
            {"Index","System Information Utility","Control Panel"},
            {"Executive services","Patches","File attributes"},
            {"File type","Folder","Root directory"},
            {"Use System Restore","Use the Search box","Use the Start menu"},
            {"GUI","Picture","none"},
            {"true","false","none"},
            {"true","false","none"},
            {"Device Manager","BIOS","Operating systems"},
            {"true","false","none"},
            {"Device drivers","Device managers","none"},
            {"System Preferences","Properties","Spotlight"},
            {"Windows NT","Windows XP","Windows Me"},
            {"Windows Me","DOS","Windows 3.1"},
            {"Taskbar","Kernel","Registry"},
            {"Keystroke shortcuts","Keyboard preferences","Icons"},
            {"Windows Explorer","File attributes","Device Manager"},
            {"Control Panel","Virtual Machine","Task Manager"},
            {"Icon-driven","Command-driven","DOS-driven"},
            {"Windows 2000","Windows XP","Windows NT"},
            {"true","false","none"},
            {"Skinny","NTFS","Pancakes"},
            {"1","2","3"},
            {"Service pack","Windows 2000","Windows XP"},
            {"Application Software","Database System","Operating System"},
            {"Windows NT","Windows 98","MS DOS"},
            {"new file","another running process","log file"},

            //ch3
            {"uniprogramming systems","uniprocessing systems","unitasking systems"},
            {"pending alarms, signals and signal handlers","all of the mentioned"},
            {"fork","create","new"},
            {"killed by another process","fatal error","all of the mentioned"},
            {"scheduled to run after execution","when process is using the CPU","none"},
            {"communication within the process","communication between two process","none"},
            {"process is blocked and will remain forever","each process is terminated","none"},
            {"Local variables","Return addresses","PID of child process"},
            {"wait","exit","fork"},
            {"Program counter","CPU registers","Process stack"},
            {"output","throughput","capacity"},
            {"new","old","waiting"},
            {"Process type variable","A Block in memory","Data Structure"},
            {"Process Table","Program Counter","Process Register"},
            {"only one task at a time","multiple tasks at a time","only two tasks at a time"},
            {"Job Queue","PCB queue","Device Queue"},
            {"block","wakeup","dispatch"},
            {"context switch time","the process state","none"},
            {"device","timer","scheduler process"},
            {"cooperating process","child process","parent process"},
            {"Process Control Block","Device Queue","Process Identifier"},
            {"orphan","zombie","body"},
            {"wait","fork","exec"},
            {"normally","abnormally","none"},
            {"have to be of fixed size","have to be variable size","can be fixed or variable sized"},
            {"communication link","message-passing link","synchronization link"},
            {"Programmed buffering","Automatic buffering","User defined buffering"},
            {"message system with buffering","message system with no buffering","none"},
            {"receive & send message","write & delete message","none"},
            {"queue can store only one message","sender blocks until receiver receive msg","none"},
            //ch4
            {"program counter","stack","both"},
            {"single threaded","multithreaded","both"},
            {"thread moves to the ready queue","thread completes","none"},
            {"first thread of the process","first two threads of the process","all threads within the process"},
            {"running","parsing","ready"},
            {"terminates","blocks","unblocks"},
            {"Extending Thread class","Implementing Runnable interface","both"},
            {"execute()","run()","main()"},
            {"10","12","5"},
            {"run()","execute()","start()"},
            {"start()","run()","execute()"},
            {"1","2","3"},
            {"join()","sleep()","wait()"},
            {"5","1","0"},
            {"isAlive()","run()","alive()"},
            {"1, 10","0,10","0,255"},
            {"Run()","start()","execute()"},
            {"Background","foreground","both"},
            {"setDaemon(boolean value)","setThread(boolean value)","none"},
            {"sleep()","wait()","join()"},
            {"run()","start()","wait()"},
            {"JRE","JVM","JDK"},
            {"runningThread()","currentThread()","none"},
            {"Process based","thread based","both"},
            {"integer","float","double"},
            //ch 5
            {"Scheduler","Dispatcher","kernel"},
            {"job queue","ready queue","process queue"},
            {"Short term scheduler","Long term scheduler","none"},
            {"stack ","tree","queue"},
            {"SJF – Non preemptive","SJF – preemptive","none"},
            {"deadlock","aging","starvation"},
            {"Non-preemptive scheduling","preemptive scheduling","none"},
            {"are appropriate for large computers","use minimal resources","all"},
            {"earliest due date","slack time remaining","first come first served"},
            {"First come First served","Shortest Job First","none"},
            {"kernel","user-level thread","none"},
            {"fcfs","critical ratios","none"},
            {"fcfs","sjf","none"},
            {"Cpu bursts many short","Cpu bursts a few short","Cpu bursts a few longer"},
            {"FCFS scheduling","priority scheduling","none"},
            {"waiting time"," response time","turnaround time"},
            {"Preemptive scheduling","Non-Preemptive scheduling","none"},
            {"interrupt","scheduler","dispatcher"},
            {"Throughput","flaps","MHz"},
            {"Dispatcher","short term schedular","long term schedular"},
            {"Long term scheduling","short term scheduling","none"},
            {"Long term scheduling","short term scheduling","none"},
            {"Long term scheduling","short term scheduling","none"},
            {"Feedback","SJF","none"},
            {"FCFS","SJF","none"},
            //ch6
            {"cooperating process","child process","parent process"},
            {"semaphore","thread","pipe"},
            {"cant drop below 0","cant more than 0","none"},
            {"mutex locks","binary semaphores","both"},
            {"hardware level","software level","both"},
            {"shared data structure","synchronization","all"},
            {"data consistency","data insecurity","data inconsistency"},
            {"Mutual Exclusion","progress","all"},
            {"single","atomic","static"},
            {"periodically","atomically","none"},
            {"hardware for system","special program","integer variable"},
            {"wait","stop","hold"},
            {"stop()","block()","hold()"},
            {"continue()","wakeup()","getup()"},
            {"remainder section code","non critical section code","critical section code"},
            {"Starvation","Deadlock","Aging"},
            {"mutex & counting","binary & counting","none"},
            {"1","-1","0"},
            {"System calls","IPC mechanisms","none"},
            {"Mutual Exclusion","Bounded Waiting","none"},
            {"semaphore","high level synchronization","none"},
            {"wait & signal","wait & hold","none"},
            {"transaction","operation","function"},
            {"a log record","a memory","a system"},
            {"growing & shrinking","shrinking & creation","none"},
            //ch7
            {"elevator algorithm","round-robin algorithm","banker’s algorithm"},
            {"starvation","deadlock","aging"},
            {"resource allocation graph","starvation graph","inversion graph"},
            {"system calls","interrupt","none"},
            {"lesser prone to deadlocks","more prone to deadlocks","none"},
            {"Mutual exclusion","No preemption","all"},
            {"must exist","must not exist","none"},
            {"is required","is not required","none"},
            {"safe sequence","safe allocation","safe resource"},
            {"not deadlocks","deadlocks","fatal"},
            {"less efficient","more efficient","equal"},
            {"Available","need","all"},
            {"Allocation – Available","Max – Available","Max – Allocation"},
            {"rarely","frequently","both"},
            {"increase","drop","stay still"},
            {"is more time consuming","incurs minimum cost","both"},
            {"priority of the process","process is interactive","both"},
            {"aborted","rolled back","terminated"},
            {"abort the process","roll back the process","both"},
            {"starvation","aging","deadlock"},
            {"Reusable Resource","Single Process Resource","Consumable Resource"},
            {"Reusable Resource","Single Process Resource","Consumable Resource"},
            {"Mutual Exclusion","hold and wait","none"},
            {"Detection","prevention","avoidance"},
            {"Circular Wait","Mutual Exclusion","hold and wait"},
            //ch8
            {"program counter","status register","both"},
            {"cache","accumulator","stack pointer"},
            {"physical address","absolute address","logical address"},
            {"Memory management unit","CPU","PCI"},
            {"stack pointer","page table base register","page register"},
            {"logical address","physical address","both"},
            {"base address","page size","page offset"},
            {"each process","each instruction","each thread"},
            {"Logical address","physical address","none"},
            {"Logical address","physical address","none"},
            {"basic register","regular register","relocation register"},
            {"physical memory","external storage","both"},
            {"motherboard","monitor","backing store"},
            {"waiting","transfer","execution"},
            {"as a chunk of disk","into a file system","both"},
            {"operating system","CPU","both"},
            {"less than","equal to","greater than"},
            {"changes","increases","decreases"},
            {"exactly one process","atleast one process","none"},
            {"number of partitions","CPU utilization","none"},
            {"frames","paging","none"},
            {"frames","pages","none"},
            {"page number","frame bit","both"},
            {"page","process","memory"},
            {"power of 2","power of 4","none"},
         };



    private String mCorrectAnswers[] = {"Hardware", "program control", "clustering", "WAN","can not",
                                        "time sharing","singly","doubly","circularly","stack",
                                        "FIFO","tree","two","event","bit",
                                        "trap","one","n","medium","mobile computing",
                                        "compute","file","cloud","to do inter process communication","FIFO",
                                        "SJF","size of address bus","FCFS","MS DOS","AU/X",
                                        "Spooler","DOS","booting","Schedular Process","deadlock avoidance",
                                        "program","FIFO","Processor","Data Transfer","1",
            //c2
                                        "Directories,sub directories and files","Distributions","Operating system","true","System Information Utility",
                                        "File attributes","File type","Use System Restore","GUI","false",
                                        "true","Device Manager","true","Device drivers","System Preferences",
                                        "Windows XP","DOS","Taskbar","Keystroke shortcuts","Device Manager",
                                        "Control Panel","Command-driven","Windows XP","true","NTFS",
                                        "3","Service pack","Operating System","MS DOS","new file",
            //ch3
                                        "uniprocessing systems","all of the mentioned","fork","all of the mentioned","scheduled to run after execution",
                                        "communication between two process","process is blocked and will remain forever","PID of child process","wait","Program counter",
                                        "throughput","old","Data Structure","Process Table","only one task at a time",
                                        "PCB queue","block","context switch time","scheduler process","cooperating process",
                                        "Process Identifier","zombie","wait","normally","can be fixed or variable sized",
                                        "communication link","Automatic buffering","message system with no buffering","receive & send message","sender blocks until receiver receive msg",
            //ch4
                                        "both","both","thread moves to the ready queue","all threads within the process","parsing",
                                        "terminates","both","run()","10","run()",
                                        "start()","2","join()","5","isAlive()",
                                        "1, 10","Run()","Background","setDaemon(boolean value)","join()",
                                        "run()","JVM","currentThread()","both","integer",
            //ch5
                                        "Dispatcher","ready queue","Short term scheduler","queue","SJF – Non preemptive",
                                        "starvation","preemptive scheduling","are appropriate for large computers","first come first served","Shortest Job First",
                                        "user-level thread","fcfs","sjf","Cpu bursts a few longer","FCFS scheduling",
                                        "turnaround time","Preemptive scheduling","dispatcher","Throughput","Dispatcher",
                                        "short term scheduling","Long term scheduling","Long term scheduling","Feedback","FCFS",
            //ch6
                                        "cooperating process","semaphore","cant drop below 0","both","both",
                                        "all","data inconsistency","all","atomic","atomically",
                                        "integer variable","wait","block()","wakeup()","critical section code",
                                        "Deadlock","binary & counting","1","IPC mechanisms","Bounded Waiting",
                                        "high level synchronization","wait & signal","transaction","a log record","growing & shrinking",
            //ch7
                                        "banker’s algorithm","starvation","resource allocation graph","system calls","more prone to deadlocks",
                                        "all","must exist","is not required","safe sequence","not deadlocks",
                                        "less efficient","all","Max – Allocation","frequently","drop",
                                        "incurs minimum cost","both","rolled back","roll back the process","starvation",
                                        "Consumable Resource","Consumable Resource","Mutual Exclusion","Detection","Circular Wait",
            //ch8
                                        "program counter","cache","logical address","Memory management unit","page table base register",
                                        "logical address","base address","each process","Logical address","physical address",
                                        "relocation register","physical memory","backing store","transfer","as a chunk of disk",
                                        "operating system","less than","changes","exactly one process","number of partitions",
                                        "frames","pages","page number","page","power of 2",

    };




    public String getQuestion(int a) {
        String question = mQuestions[a];
        return question;
    }


    public String getChoice1(int a) {
        String choice0 = mChoices[a][0];
        return choice0;
    }


    public String getChoice2(int a) {
        String choice1 = mChoices[a][1];
        return choice1;
    }

    public String getChoice3(int a) {
        String choice2 = mChoices[a][2];
        return choice2;
    }

    public String getCorrectAnswer(int a) {
        String answer = mCorrectAnswers[a];
        return answer;
    }

}
